TravelBlog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBEntity;
using TBRepo;

namespace TravelBlog.Controllers
{
    public class AdminController : AdminBaseController
    {
        private AdminRepository repo = new AdminRepository();
        private UserRepository urepo = new UserRepository();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Profile()
        {
            Admin admin = new Admin();
            admin = this.repo.Info(Session["AdminEmail"].ToString());
            return View(admin);
        }

        [HttpGet]
        public ActionResult Edit(Admin admin)
        {
            admin = this.repo.Info(Session["AdminEmail"].ToString());
            return View(admin);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            if(collection["fname"] != "" && collection["lname"] != "" && collection["phone"] != "" && collection["address"] != "")
            {
                Admin admin = new Admin();
                admin.Email = Session["AdminEmail"].ToString();
                admin.FirstName = collection["fname"];
                admin.LastName = collection["lname"];
                admin.Phone = collection["phone"];
                admin.Division = collection["division"];
                admin.Address = collection["address"];
                this.repo.Update(admin);
                return RedirectToAction("Profile");
            }
            else
            {
                return Content("Please fill all the field");
            }
        }

        [HttpGet]
        public ActionResult ChangePassword(Admin admin)
        {
            admin = this.repo.Info(Session["AdminEmail"].ToString());
            return View(admin);
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection collection)
        {
            string newPass, confirmNewPass;
            User user = new User();
            user.Email = Session["Email"].ToString();
            user.Password = collection["cpass"];
            newPass = collection["npass"];
            confirmNewPass = collection["cnpass"];
            bool correctOldPass = repo.CheckOldPass(user.Email, user.Password);
            if (correctOldPass)
            {
                if (newPass == confirmNewPass)
                {
                    this.repo.ChangePass(Session["AdminEmail"].ToString(), newPass);
                }
                else
                {
                    return Content("Password doesn't match");
                }
            }
            else
            {
                return Content("Please enter the current password correctly");
            }
            return RedirectToAction("ChangePassword");
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(FormCollection collection)
        {
            if(collection["fname"] != "" && collection["lname"] != "" && collection["email"] != "" && collection["phone"] != "" && collection["address"] != "" && collection["password"] != "")
            {
                Admin admin = new Admin();
                admin.FirstName = collection["fname"];
                admin.LastName = collection["lname"];
                admin.Email = collection["email"];
                admin.Phone = collection["phone"];
                admin.Division = collection["division"];
                admin.Address = collection["address"];
                admin.Password = collection["password"];
                bool existAdmin = repo.IsExistAdmin(admin.Email);
                if (!existAdmin)
                {
                    this.repo.Insert(admin);
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Admin with this email is already exist");
                }
            }
            else
            {
                return Content("Please fill all the field");
            }
            
        }

        public ActionResult UserList()
        {
            return View(this.urepo.GetAllUser());
        }

        [HttpGet]
        public ActionResult UserDetails(int id)
        {
            User u = this.urepo.GetUser(id);
            return View(u);
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            User u = this.urepo.GetUser(id);
            return View(u);
        }

        [HttpPost][ActionName("DeleteUser")]
        public ActionResult DeleteConfirmed(int id)
        {
            this.urepo.DeleteUser(id);
            return RedirectToAction("UserList");
        }

        public ActionResult AdminList()
        {
            return View(this.repo.GetAllAdmin());
        }

        [HttpGet]
        public ActionResult AdminDetails(int id)
        {
            Admin a = this.repo.GetAdmin(id);
            return View(a);
        }

        [HttpGet]
        public ActionResult DeleteAdmin(int id)
        {
            Admin a = this.repo.GetAdmin(id);
            return View(a);
        }

        [HttpPost]
        [ActionName("DeleteAdmin")]
        public ActionResult DeleteConf(int id)
        {
            this.repo.DeleteAdmin(id);
            return RedirectToAction("AdminList");
        }

        public ActionResult SignOut()
        {
            Session.Remove("AdminEmail");
            return RedirectToAction("Index", "Default");
        }
    }
}

TravelBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TBEntity;
using TBRepo;

namespace TravelBlog.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        private TBReposetory repo = new TBReposetory();
        private UserRepository urepo = new UserRepository();
        private BlogRepo brepo = new BlogRepo();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SBlog()
        {
            return View(this.brepo.GetBlog());

        }
        public ActionResult ABlog()
        {

            return View(this.brepo.GetBlog());
        }
        public ActionResult SrcBlog(FormCollection collection)
        {
            string searchString = collection["SResult"];
            return View(this.brepo.SearchBlog(searchString));
        }
        public ActionResult SaveBlog(FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                Blog blog = new Blog();
                blog.Title = collection["name"];
                blog.Address = collection["email"];
                blog.blog = collection["blog"];
                blog.WriterName = (string)Session["name"];
                blog.WriterId=(int)Session["Id"];
                Session["ublog"] = blog;
                this.brepo.BlogUpdate(blog);
                return RedirectToAction("UBlog","User");
            }
            else
            {
                collection["name"] = "";
                return View("Register");
            }
        }
        [HttpGet]
        public ActionResult BlogDetails(int id)
        {
            Blog a = this.brepo.GetBlog(id);
            return View(a);
        }

        [HttpGet]
        public ActionResult DeleteBlog(int id)
        {
            Blog a = this.brepo.GetBlog(id);
            return View(a);
        }

        [HttpPost]
        [ActionName("DeleteBlog")]
        public ActionResult DeleteConf(int id)
        {
            this.brepo.DeleteBlog(id);
            return RedirectToAction("Index");
        }
    }
}

TravelBlog/Views/Shared/Admin_Navbar.cshtml
@model TBEntity.Admin

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
</head>
<body style="height:1500px">
    @RenderBody()
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top" style="position: fixed;top: 0;width: 100%;">
        <ul class="navbar-nav">
            <li class="nav-item" style="margin-right:15px;margin-left:8px">
                <a class="nav-link" href="@Url.Action("Index", "Admin",Model)">Home</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("Profile", "Admin")">Profile</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("AddAdmin", "Admin",Model)">Add Admin</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("UserList", "Admin",Model)">User List</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("AdminList", "Admin",Model)">Admin List</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("ABlog", "Blog")">Manage Blogs</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("SignOut", "Admin")">Sign Out</a>
            </li>
        </ul>
    </nav>

</body>
</html>

TravelBlog/Views/Shared/_Navber.cshtml
@model TBEntity.User
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
</head>
<body style="height:1500px">
    @RenderBody()
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top" style="position: fixed;top: 0;width: 100%;">
        <ul class="navbar-nav">
            <li class="nav-item" style="margin-right:15px;margin-left:8px">
                <a class="nav-link" href="@Url.Action("Index", "User",Model)">Home</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("Profile", "User")">Profile</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("Settings", "User")">Settings</a>
            </li>

            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("UBlog", "User")">Blog</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item" style="margin-right:15px">
                <a class="nav-link" href="@Url.Action("SignOut", "User")">Sign Out</a>
            </li>
            <form class="form-inline" style="margin-left:380px" action="/Blog/SrcBlog" method="post">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Blogs " id="SResult" style="width:225px" name="SResult">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
        </ul>
    </nav>

</body>
</html>